### ISSUE TITLE
review

### ISSUE THREAD

**Issue by leej3** [DataChicken77/Will_Horne_Solo_Project#2]
Terrific job. Well done.

Regarding grading, the only thing you would currently lose marks for is modularity. i.e. instead of just the local_functions.py module you should group functions by what they do. As in have a `plotting.py`, `cleaning.py`, `utils.py`,`data_ingestion.py` and sort of thing. That just means as the project grows it doesn't become one big mess and instead functionality roughly correlates with the modules you have specified.

Other general feedback:
+ You might want to check out the plotting library Seaborn at some point. It lacks the customization abilities of matplotlib  but it typically looks nicer and can make the job easier. You can even just load Seaborn and your matplotlib figures inherit a lot of the pleasing default settings of Seaborn...
+ In the notebook you have the line:
`lf.analyze_cfu_counts("../will_horne_solo_project/IR_Datasets/A-baumannii_AB5075.xlsx",0.005)`

This would be better as:
```
datafile = '../will_horne_solo_project/IR_Datasets/A-baumannii_AB5075.xlsx'
lf.analyze_cfu_counts(datafile,0.005)
```
The above code is clearer, prevents you running over pep8's character limit, and as code moves about/gets shifted to functions etc. it makes it easier to spot what variables should be inputs to the function and  so eases that process
+ Adding install instructions for your package is always a kindness to someone who happens upon your repository and decides that they could use it for their own. work.
+ Storing data in a single location is typically a good practice. Keeping it minimal is also good. If it is just for tests then putting it in tests/data would be good. But it could also go in the root directory. Alternatively, you might. actually want it available for people using your package in which case you would move it. into the Will_Horne_Solo_Project subdirectory.
+ Taking note of what should be including online would be good. For example egg-info, pycache, ipynb checkpoints should not be  committed to the repository. They bloat the repository and they are  often ways for sensitive information to leak into your online code.

**Comment by DataChicken77** [comment]
Thank you for the feedback!

I will definitely look at my `local_functions.py` module and separate it according to functionality.

Once I finish up with all other tweaks, I'll look at Seaborn to improve the quality of my plots.  Would it be safe to import both Seaborn and matplotlib?

I'll streamline the inputs to my functions in the notebook.

For install instructions, would I include those in the README.md?

I'll move the /IR_Dataset directory up a level, on par with the /test and /notebook directories.  It will simplify the relative file paths I'll have to pass in the notebook.

Thank you for pointing out the files I don't need to archive.  I will `git ignore` them as soon as possible.

**Comment by leej3** [comment]
> Once I finish up with all other tweaks, I'll look at Seaborn to improve the quality of my plots. Would it be safe to import both Seaborn and matplotlib?

yep. Seaborn is a layer on top of matplotlib. It attempts to reduce the effort required to create plots. It's great. Often people want more customization for their plots though... then you are back to matplotlib. You will likely jump back and forth between the two depending on what you need.


> For install instructions, would I include those in the README.md?

Yep.

**Comment by DataChicken77** [comment]
Update:

- `local_functions.py` expanded to `clean.py`, `display.py`, `extract.py`, and `process.py`.

- Notebook code streamlined for readability.

- /IR_Dataset directory now in main repository directory.

For further clarity, if I `git rm` the files and directories you mentioned at the top, will that disrupt any `git` functionality?

**Comment by DataChicken77** [comment]
Update:

- Added module installation instructions to README.md.

**Comment by leej3** [comment]
Nice improvements.

> For further clarity, if I git rm the files and directories you mentioned at the top, will that disrupt any git functionality?

The beauty of git is that it is hard to lose things. provided files/changes have been added to the git repository (via `git commit`) it is very hard to lose them. `git rm` or `rm` will always be salvageable. Test out the various combinations and see what works best.

I think you might be a little muddled on install/import/package terms. Have a look through this to see if it resolves things for you:
https://realpython.com/python-modules-packages/

**Comment by leej3** [comment]
Excellent job again with this. Very impressive. I hope it proves useful.

Just some feedback to bear in mind in future (didn't mention it and it certainly isn't a big deal regarding marking)

+ use Pep8. This style guide describes good "style" in python. Often "linters" can be very helpful in giving you feedback and even reformatting your code in a compliant manner. If you are using python a lot, choosing a tool like PyCharm will help with this. You can also use command line tools that will do the same thing.
+ functions should be small. around 20 lines max. As you write more code you should have that in mind. Typically what fits on a laptop monitor  is considered the maximum length of a function. After that the benefits of modularity begin to not be felt so much (if nothing else people don't like scrolling up and down to understand a chunk of code)
+ stray datafilee should be stored in a directory. making a "data" directory in the root directory or in the tests directory might be useful locations for this.
